ryanrealestate/config/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views import static

from . import settings

urlpatterns = [
    url(
        r'^media/(?P<path>.*)$',
        static.serve,
        {'document_root': settings.MEDIA_ROOT},
    ),
    url(
        r'^admin/',
        admin.site.urls
    ),
    url(
        r'^listings/',
        include(
            'listings.urls',
            namespace='listings'
        ),
    ),
    url(
        r'^news/',
        include(
            'news.urls',
            namespace='news',
        ),
    ),
    url(
        r'^',
        include(
            'home.urls',
            namespace='home',
        ),
    ),
    url(
        r'',
        include(
            'pages.urls',
            namespace='pages',
        ),
    ),
]

ryanrealestate/home/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(
        r'^$',
        views.HomeView.as_view(),
        name='home',
    ),
]

ryanrealestate/pages/templates/pages/contact.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    <div class="col-1-1">
        <h1 class="center">{{page_title}}</h1>
        <hr class="divider">
        {{page.page_description|safe}}
    </div>
</div>
<div class="row">
    <div class="col-3-5 center">
        <form id="contact-form" method="post">
            {% csrf_token %}
            <div class="row">
                <div class="col-1-3">
                    {{contact_form.name.label_tag}}<br>
                    {{contact_form.name}}
                </div>
                <div class="col-1-3">
                    {{contact_form.company.label_tag}}<br>
                    {{contact_form.company}}
                </div>
                <div class="col-1-3">
                    {{contact_form.email.label_tag}}<br>
                    {{contact_form.email}}
                </div>
            </div>
            <div class="row">
                <div class="col-1-1">
                    {{contact_form.message.label_tag}}<br>
                    {{contact_form.message}}
                </div>
            </div>
            <div class="row">
                <div class="col-1-1">
                    <input id="contact-submit" type="submit" value="Send"/>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

ryanrealestate/pages/templates/pages/content_page.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block content %}
{{instance.body|safe}}
{% endblock %}

ryanrealestate/pages/templates/pages/thank_you.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    <div class="col-3-5 center">
        <h2 class="center">Thanks for contacting Us!</h2>
        <p class="center">We will get back to you as soon as possible.</p>
        <p class="center" style="margin-top: 40px;"><a href="{% url 'home:home' %}" class="cta-medium">HOME</a></p>
    </div>
</div>
{%endblock %}